Ignore apt update errors

diff --git a/.github/workflows/run_scrapers.yml b/.github/workflows/run_scrapers.yml
--- a/.github/workflows/run_scrapers.yml
+++ b/.github/workflows/run_scrapers.yml
@@ -53,11 +53,16 @@ jobs:
       run: |
         for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
     - name: Install dependencies
+      env:
+        SCRAPER_KEY: ${{ matrix.canton }}
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
-        sudo apt update
-        sudo apt-get install sqlite3 poppler-utils
+        sudo apt update || true # do not fail if update does not work
+        sudo apt-get install sqlite3
+        if [ "$SCRAPER_KEY" = "FL" ] ; then
+          sudo apt-get install poppler-utils
+        fi
 
     - name: Scrape new data
       env:
