Run `apt-get update` before installation

diff --git a/.github/workflows/test_scraper.yml b/.github/workflows/test_scraper.yml
--- a/.github/workflows/test_scraper.yml
+++ b/.github/workflows/test_scraper.yml
@@ -26,12 +26,17 @@ jobs:
       with:
         python-version: 3.7
 
+    - name: Remove broken apt repos
+      run: |
+        for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
+
     - name: Install dependencies
       run: |
         npm ci
         python -m pip install --upgrade pip setuptools wheel
         pip install -r requirements.txt
         pip install -r requirements-ocr.txt
+        sudo apt update || true # do not fail if update does not work
         sudo apt-get install poppler-utils
 
     - name: Test run of all scrapers
